### ISSUE TITLE
Extended flow queries hang with pgpool 4.1

### ISSUE THREAD

**Issue by lyxgy841** [pgjdbc/r2dbc-postgresql#341] opened 2020-10-20 01:13 UTC
#### Versions

- Driver: 0.8.5.RELEASE
- Database: postgreSQL cluster with pgpool 4.1 (pgpool 4.0 works)
- Java: jdk8
- OS: win10

#### Current Behavior
I hava a PostgreSql cluster with Pgpool-II, other services connected to Pgpool using jdbc can run normally,  but service using 
r2dbc connect to pgpool, queries just hang forever.

**Comment by mp911de** [comment] 2020-10-20 06:50
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by lyxgy841** [comment] 2020-10-20 09:10
this is demo https://github.com/lyxgy841/r2dbc-demo

**Comment by mp911de** [comment] 2020-11-04 14:03
Thanks a lot. Here's an excerpt from the logs:

```
2020-11-04 14:59:13.678 DEBUG 45353 --- [actor-tcp-nio-9] i.r.p.client.ReactorNettyClient          : [cid: 0x6][pid: 1307] Response: ReadyForQuery{transactionStatus=IDLE}
2020-11-04 14:59:13.743 DEBUG 45353 --- [           main] io.r2dbc.postgresql.PARAM                : [cid: 0x6][pid: 1307] Bind parameter [0] to: Dave
2020-11-04 14:59:13.745 DEBUG 45353 --- [           main] io.r2dbc.postgresql.PARAM                : [cid: 0x6][pid: 1307] Bind parameter [1] to: Matthews
2020-11-04 14:59:13.749 DEBUG 45353 --- [           main] i.r.p.client.ReactorNettyClient          : [cid: 0x6][pid: 1307] Request:  [Parse{name='S_0', parameters=[1043, 1043], query='INSERT INTO customer (firstname, lastname) VALUES ($1, $2) RETURNING *'}, Flush{}]
```

The conversation stops after the flush request (P/H). Looking at JDBC, the sequence consists of Parse, Bind, Desc, Execute,  Sync (P/B/D/E/S). While we do not combine all packets, it looks like we should include `Sync`. Going to test that.

**Comment by mp911de** [comment] 2020-11-04 14:23
Interestingly, this issue happens with PGPool 4.1 but not with PGPool 4.0.x.

**Comment by mp911de** [comment] 2020-11-04 14:29
To achieve a similar flow as with PGJDBC, we would need to change our statement caching API in the way that we generate a statement name but do not await `ParseComplete` before continuing with the flow. Instead, we should get hold of the parse message to append bind, desc etc.. We would have to register the prepared statement only when we receive `ParseComplete`.

**Comment by m4tt87** [comment] 2020-11-16 16:05
Hi @mp911de,
I found the same problem in the past. To solve it, only as a workaround, I used the following dependencies:

implementation 'org.springframework.boot.experimental:spring-boot-starter-data-r2dbc:0.1.0.M3'.
implementation 'io.r2dbc:r2dbc-pool:0.8.0.RELEASE'.
implementation 'io.r2dbc:r2dbc-postgresql:0.8.0.RELEASE'.
Any subsequent version of r2dbc-postgresql caused the problem.
PGPool version: 4.1.4

I recently tried to upgrade to the latest available version of spring-boot-starter-data-r2dbc, r2dbc-pool, and r2dbc-postgresql and the problem persists.

I hope that this additional information will help you in solving the problem.

**Comment by mp911de** [comment] 2020-12-16 10:41
I had a look what it takes to make this work with pgpool 4.1.

We need to rewrite our query flow and change conceptually how the statement cache works. Basically, the cache needs to supply only details and no more initiate the query parsing on its own.

Beyond that, we're using an optimized flow with cursors that creates a cursor even in auto-commit mode. That is because we use  `Execute` + `Flush` instead of `Execute` + `Sync`. That works pretty well when using a Postgres server directly. Pgpool fails to respond since version 4.1.

That means we require a compatibility mode where we use `Execute` + `Sync`. It's a pretty significant change. While the compatibility mode aligns with what PGJDBC does, we should not enable compatibility mode by default.

I have got a working prototype locally, but it would be good to get some reviewers once I can submit a PR.

**Comment by Squiry** [comment] 2020-12-17 20:06
> it would be good to get some reviewers once I can submit a PR
I beleive I can help you with that.

**Comment by mp911de** [comment] 2020-12-18 13:40
I submitted #373 containing the changes.

**Comment by dave-b-uk** [comment] 2021-01-05 14:55
Hello,

Do you know when will this fix be released?

**Comment by mp911de** [comment] 2021-01-05 15:03
#373 needs more reviews first before we can go into planning. Other than that, you can find release dates in the [milestones](https://github.com/pgjdbc/r2dbc-postgresql/milestones).

**Comment by dave-b-uk** [comment] 2021-01-05 15:05
Thanks for the heads up @mp911de !

**Comment by mp911de** [comment] 2021-02-18 10:39
That's fixed now.

**Closed by mp911de** 2021-02-18 10:39 UTC
Labels: type: task
