### ISSUE TITLE
Does Codec decoding need to be aware of the target type?

### ISSUE THREAD

**Issue by gregturn** [pgjdbc/r2dbc-postgresql#168] opened 2019-09-24 15:12 UTC
When extracting a value from a column (decoding), selecting a Codec is currently based on the data type of the column. There is no consideration for the end result type.

Is this necessary? Recent issues regarding multiple target types that are all stored the same in tables imply there should be.

NOTE: This issue was ALSO observed in `r2dbc-h2`, which borrowed Codec solution from this project.

**Comment by mp911de** [comment] 2019-09-24 15:17
Decoding in Postgres is based on three factors:

* The column type (type OID)
* The format in which the data is encoded (binary or text)
* The requested value type (`Object` or a more specific variant such as `String`)

A codec may support multiple formats and OIDs and only a single Java type (that is the current restriction of `AbstractCodec`). For e.g. numeric codecs we have [`AbstractNumericCodec`](https://github.com/r2dbc/r2dbc-postgresql/blob/master/src/main/java/io/r2dbc/postgresql/codec/AbstractNumericCodec.java), capable of decoding all possible numeric types and concrete subclasses for each individual Java type such as [`IntegerCodec`](https://github.com/r2dbc/r2dbc-postgresql/blob/master/src/main/java/io/r2dbc/postgresql/codec/IntegerCodec.java).

**Comment by mp911de** [comment] 2022-01-11 09:22
Closing as the issue is no longer applicable. Codecs can produce multiple target types.

**Closed by mp911de** 2022-01-11 09:22 UTC
Labels: for: team-attention
