### ISSUE TITLE
afterExecuteQuery ran before query end

### ISSUE THREAD

**Issue by deblockt** [pgjdbc/r2dbc-postgresql#414] opened 2021-06-04 14:25 UTC
#### Versions

- Driver: r2dbc-postgres 0.8.6 poxy 0.8.3 spi 0.8.3
- Database: postgres
- Java: java 11
- OS: max

#### Current Behavior

the afterExecuteQuery is called before end of the query execution mono, so when we use it to report execution time, the result is bad

```
2021-06-04 12:21:12.202 START THE QUERY
2021-06-04 12:21:12.202 Executing SQL statement [select data from myTable where id = :id LIMIT 1]
2021-06-04 12:21:12.203 Expanding SQL statement [select data from myTable where id = :id LIMIT 1] to [select data from myTable where id = $1 LIMIT 1]
2021-06-04 12:21:12.203 beforeExecuteQuery > start the query select data from myTable where id = $1 LIMIT 1
2021-06-04 12:21:12.246 afterExecuteQuery > end the query select data from myTable where id = $1 LIMIT 1
2021-06-04 12:21:12.687 DATA LOADED
```
On this logs we can see the the afterExecuteQuery is called 400ms before the end of the mono.

#### Steps to reproduce

This code is used to reproduce the issue: 
``` java
final var sql = "select data from myTable where id = :id LIMIT 1";

return Mono.defer(() -> log.info("START THE QUERY"))
    .then(
      this.databaseClient.execute(sql)
    .bind("id", myObject.toString())
    .map(row -> row.get("data", String.class))
    .one())
    .doOnNext(paymentExecution -> log.info("DATA LOADED"));
```

I'm not sur that the issue is on this project or on the postgres driver. 

The query is slow because the table is bug > 3Go and an index is missing. 

#### Expected behavior/code

the method afterExecuteQuery should be called when the query is ended and the result fetched.

**Comment by deblockt** [comment] 2021-06-04 14:25
I tried to use the `ProxyMethodExecutionListener` instead of the old `LifeCycleListener` but the result is same.
I tried with this code: 
```

@Slf4j
public class TracingExecutionListener implements ProxyMethodExecutionListener {

    @Override
    public void beforeQuery(QueryExecutionInfo execInfo) {
        final var queries = execInfo.getQueries().stream()
            .map(QueryInfo::getQuery)
            .collect(joining(", "));
        log.info("TracingExecutionListener beforeQuery > start the query {}", queries);
    }

    @Override
    public void eachQueryResult(QueryExecutionInfo execInfo) {
        final var queries = execInfo.getQueries().stream()
            .map(QueryInfo::getQuery)
            .collect(joining(", "));
        log.info("TracingExecutionListener eachQueryResult > a result on the query {} {}", queries, execInfo.getExecuteDuration().toMillis());
    }

    @Override
    public void afterQuery(QueryExecutionInfo execInfo) {
        final var queries = execInfo.getQueries().stream()
        .map(QueryInfo::getQuery)
        .collect(joining(", "));
        log.info("TracingExecutionListener afterQuery > end the query {} {}ms", queries, execInfo.getExecuteDuration().toMillis());
    }
}

```

And I have a strange workflow on logs
```
2021-06-04 16:07:16.679 START THE QUERY
2021-06-04 12:21:12.202 Executing SQL statement [select data from myTable where id = :id LIMIT 1]
2021-06-04 12:21:12.203 Expanding SQL statement [select data from myTable where id = :id LIMIT 1] to [select data from myTable where id = $1 LIMIT 1]
2021-06-04 16:07:16.711 TracingExecutionListener beforeQuery > start the select data from myTable where id = $1 LIMIT 1
2021-06-04 16:07:16.727 TracingExecutionListener afterQuery > end the select data from myTable where id = $1 LIMIT 1 15ms
2021-06-04 16:07:17.336 TracingExecutionListener eachQueryResult > a result on the select data from myTable where id = $1 LIMIT 1 15
```

the `afterQuery` is called before the `eachQueryResult` and the request duration seem bad (15ms)

**Comment by deblockt** [comment] 2021-06-07 08:03
I'm creating a reproducer projet. 
I can see that the issue happen only when using a binded var. When I use spring integration
This code works: 
```
        return Mono.fromRunnable(() -> log.info("before executing query mono"))
            .then(
                databaseClient.execute("select data from my_table where id = 'b8b4304f-9db7-4c8c-b690-4e6338a4de83' FOR UPDATE LIMIT 1")
                    .map(row -> row.get("data", String.class))
                    .one()
            ).doOnNext($ -> log.info("after execute the query mono"));
```

This code produce the issue:
```
        return Mono.fromRunnable(() -> log.info("before executing query mono"))
            .then(
                databaseClient.execute("select data from my_table where id = :id FOR UPDATE LIMIT 1")
                    .bind("id", "b8b4304f-9db7-4c8c-b690-4e6338a4de83")
                    .map(row -> row.get("data", String.class))
                    .one()
            ).doOnNext($ -> log.info("after execute the query mono"));
```

**Comment by mp911de** [comment] 2021-06-07 09:17
Duplicate of https://github.com/r2dbc/r2dbc-proxy/issues/94

**Closed** 2021-06-07 09:20 UTC
Labels: for: external-project, status: duplicate, status: waiting-for-triage
