### ISSUE TITLE
Compatibility/Bug in r2dbc-postgresql v1.0.5 due to performance tuning

### ISSUE THREAD

**Issue by markus-arndt-fioneer** [pgjdbc/r2dbc-postgresql#663] opened 2024-09-30 16:06 UTC
#### Versions
- Driver: Postgresql 42.6.2
- Database: PostgreSQL 11.22 (fully managed on Azure)
- Java: 17
- OS: Arch Linux

#### Current Behavior

After we have upgraded from `Spring Boot 3.2.4` to `Spring Boot 3.2.10` / from `r2dbc-postgres 1.0.4` to `r2dbc-postgres 1.0.5` we are seeing Exceptions from `PostgresqlRowMetadata.java::getColumn` which was performance tuned in that release.

 * Buggy Release: https://github.com/pgjdbc/r2dbc-postgresql/releases/tag/v1.0.5.RELEASE
 * Issue that introduced the Bug: https://github.com/pgjdbc/r2dbc-postgresql/issues/636
 * Buggy PR: https://github.com/pgjdbc/r2dbc-postgresql/commit/079b565dbb5a0b0ea8637e9d981c07cb782c2cb4

#### The exceptions we see are:

_PostgresqlConnectionFactory.java (caused by Exception below)_
```
Caused by: io.r2dbc.postgresql.PostgresqlConnectionFactory$PostgresConnectionException: Cannot connect to 4.180.61.180/<unresolved>:5432
at io.r2dbc.postgresql.PostgresqlConnectionFactory.cannotConnect(PostgresqlConnectionFactory.java:188)
at io.r2dbc.postgresql.PostgresqlConnectionFactory.lambda$doCreateConnection$7(PostgresqlConnectionFactory.java:153)
```

_PostgresqlRow.java (this was performance tuned)_
```
Caused by: java.util.NoSuchElementException: Column name 'oid' does not exist in column names [typname, typnamespace, typowner, typlen, typbyval, typtype, typcategory, typispreferred, typisdefined, typdelim, typrelid, typelem, typarray, typinput, typoutput, typreceive, typsend, typmodin, typmodout, typanalyze, typalign, typstorage, typnotnull, typbasetype, typtypmod, typndims, typcollation, typdefaultbin, typdefault, typacl]
at io.r2dbc.postgresql.PostgresqlRow.getColumn(PostgresqlRow.java:193)
at io.r2dbc.postgresql.PostgresqlRow.get(PostgresqlRow.java:96)
at io.r2dbc.postgresql.codec.BuiltinDynamicCodecs.lambda$null$0(BuiltinDynamicCodecs.java:107)
at io.r2dbc.postgresql.PostgresqlResult.lambda$map$2(PostgresqlResult.java:129)
at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:179)
... 60 common frames omitted\n
```

**Comment by mp911de** [comment] 2024-10-02 08:01
This is a duplicate of #657

**Closed by mp911de** 2024-10-02 08:01 UTC
Labels: status: duplicate
